#
# Copyright (c) 2021 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Publish release

on:
  push:
    branches:
      - 'test*'

permissions:
  contents: write

env:
  REGISTRY_USER: queter
  #REGISTRY_PASSWORD: ${{ secrets._PASSWORD }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    container: redhat/ubi8
    steps:
    - name: setup
      run: chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
    - name: Checkout the source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
        cache: true

    - name: Install git
      run: |
        dnf -y install git

    - name: Run releaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist --skip-validate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
